version: '3'
networks:
  web:
    external: true
services:
  srtdash:
    build: ./app
    image: mikeryan56/starlette-srtdash:19.8.10
    # image: mikeryan56/starlette-srtdash:latest
    restart: always
    ports:
    - "5000"
    volumes:
    - .:/code

    # if using jwilder/nginx-proxy
    # environment:
    # - VIRTUAL_HOST=srtdash.devsetgo.com
    # - LETSENCRYPT_HOST=srtdash.devsetgo.com

    #if using traefik
    labels:
    - traefik.backend=srtdash
    - traefik.frontend.rule=Host:srtdash.devsetgo.com
    - traefik.docker.network=web
    - traefik.port=5000
    networks:
      - web
  # deploy:
  #    replicas: 2
  #    resources:
  #      limits:
  #        cpus: "2"
  #        memory: 100M
#      restart_policy:
#        condition: always
