name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python: ['3.8','3.7', '3.6']
    steps:
    - uses: actions/checkout@master
    - name: Python ${{ matrix.python }} version
      uses: actions/setup-python@v2.2.2
      with:
          python-version: ${{ matrix.python }}
          architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd app
        pip install -r requirements/dev.txt
    - name: Test with pytest
      run: |
        cd app
        cp .env_sample .env
        python3 -m pytest
